In [3]:
class Vehicle:
    color = "white"

    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage
        self.seating_capacity = None

    def assign_seating_capacity(self, seating_capacity):
        self.seating_capacity = seating_capacity

    def display_properties(self):
        print("---- [Properties of the Vehicle] ----")
        print("Color:", self.color)
        print("Maximum Speed:", self.max_speed)
        print("Mileage:", self.mileage)
        print("Seating Capacity:", self.seating_capacity)

In [4]:
vehicle1 = Vehicle(200, 20)
vehicle1.assign_seating_capacity(5)
vehicle1.display_properties()

---- [Properties of the Vehicle] ----
Color: white
Maximum Speed: 200
Mileage: 20
Seating Capacity: 5


In [1]:
import numpy as np

In [2]:
a = np.array([-1,1])
b = np.array([1,1])
z = np.dot(a,b)
z

np.int64(0)

In [3]:
m = a*b
m

array([-1,  1])

In [5]:
x = np.array([[1,0,1],[2,2,2]])
out = x[0:2,2]
out

array([1, 2])

In [6]:
X=np.array([[1,0],[0,1]]) 
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])